apiVersion: v1
kind: Pod
metadata:
  name: tomcat-mysql-pod
  labels:
    app: tomcat
    db: mysql
spec:
  containers:
  - image: tomcat
    name: test-tomcat
    ports:
    - containerPort: 8080
  - image: mysql
    name: test-mysql
    ports:
    - containerPort: 3306